### ISSUE TITLE
java.sql.SQLException: [Vertica][JDBC](10180) Error fetching data, cursor positioned before first row.

### ISSUE THREAD

**Issue by sonots** [sonots/embulk-input-vertica#1]
This error appears on trying to read more than 4294967295 (2^32 - 1) rows.
It looks vertica jdbc driver handles `m_currentRows` as `int`.

**Comment by sonots** [comment]
Cannot avoid.

**Comment by Brandonage** [comment]
Hi. I have experienced the same problem recently. I'm trying to find any solution to this. Is there any that you know?. Any pointers would help, even the confirmation that there is no solution to the problem.
